"""
Name Planner for Pokemon Red

Pre-plans and stores names for:
- Player (always "LASS")
- Rival (LLM-generated funny name, with random fallback)
- Pokemon nicknames (LLM-generated for starters, optional for others)

Provides guided keyboard navigation to type names correctly.
Name generation happens at run start (rival) and Oak's lab (starter).
Keyboard navigation sequences are pre-computed for auto-execution.
"""

import logging
import random
from typing import Optional
from pyAIAgent.game.keyboard_tracker import get_keyboard_tracker

log = logging.getLogger(__name__)


# Preset suggestions for rival names (cute/silly/flirty to match Lass' persona)
# Exclude GARY as it's a preset option
RIVAL_NAME_SUGGESTIONS = [
    "CUTIE",  # Flirty
    "MEANY",  # Playful
    "BULLY",  # Teasing
    "DUMMY",  # Silly
    "CRUSH",  # Romantic
    "RIVAL",  # Classic
    "LOSER",  # Competitive
    "JERK",  # Sassy
    "STINKY",  # Juvenile humor
    "BUTT",  # Very silly
    "DORK",  # Nerdy
    "NERD",  # Geeky
    "DOOFUS",  # Goofy
    "IDIOT",  # Mean but funny
]


class NamePlanner:
    """
    Manages pre-planned names for player, rival, and Pokemon.
    Provides step-by-step keyboard navigation for typing names.

    Integration with StarterPlanner:
    - When name_type == "pokemon" and we're naming a starter, we use the
      nickname from StarterPlanner if available.
    """

    def __init__(self):
        # Player name - always LASS (character identity)
        self.player_name = "LASS"

        # Rival name - LLM-generated at run start, fallback to random
        self.rival_name: Optional[str] = None  # Will be set by name_generator
        self.rival_name_pending = False  # True when we need to pick a name
        self._rival_name_source: str = "none"  # "llm", "random", or "none"

        # Pokemon nicknames - keyed by species name
        # For starters, this is populated from StarterPlanner
        self.pokemon_nicknames: dict[str, str] = {}

        # Current starter nickname (set when entering nickname screen after getting starter)
        self._current_starter_nickname: Optional[str] = None

        # Current typing state
        self.current_name: Optional[str] = None
        self.current_char_index: int = 0
        self.typing_sequence: list[dict] = []

        # Name type detection
        self.name_type: Optional[str] = None  # "player", "rival", "pokemon"

        # State tracking
        self.confirmation_sent = (
            False  # True if we've sent the START confirmation command
        )
        self.last_confirmed_name: Optional[str] = (
            None  # The last name we successfully confirmed
        )

    def get_random_rival_name(self) -> str:
        """Pick a random funny rival name from the suggestions."""
        return random.choice(RIVAL_NAME_SUGGESTIONS)

    def detect_name_type(self, dialog_text: str, readable_text: str) -> Optional[str]:
        """
        Detect what type of name is being entered based on screen text.

        Returns: "player", "rival", "pokemon", or None
        """
        combined = (dialog_text or "").upper() + (readable_text or "").upper()

        if "YOUR NAME" in combined:
            self.name_type = "player"
            return "player"
        elif "RIVAL" in combined:
            self.name_type = "rival"
            return "rival"
        elif "NICKNAME" in combined:
            self.name_type = "pokemon"
            return "pokemon"

        return self.name_type  # Return last known type

    def get_planned_name(self) -> Optional[str]:
        """Get the name that should be typed for the current name type."""
        if self.name_type == "player":
            return self.player_name  # Always "LASS"
        elif self.name_type == "rival":
            # Use LLM-generated name if available, otherwise fallback to random
            if not self.rival_name:
                self.rival_name = self.get_random_rival_name()
                self._rival_name_source = "random"
                log.info(
                    f"NamePlanner: No preplanned rival name, using random: '{self.rival_name}'"
                )
            return self.rival_name
        elif self.name_type == "pokemon":
            # Check for starter nickname first
            if self._current_starter_nickname:
                return self._current_starter_nickname
            # Then check species-specific nicknames
            # Note: species detection would need to be passed in
            return None
        return None

    def set_preplanned_rival_name(self, name: str, source: str = "llm"):
        """
        Set the rival's name (pre-generated by LLM at run start).

        Args:
            name: The rival name (4-7 chars, uppercase)
            source: Where the name came from ("llm" or "random")
        """
        # Validate: max 7 chars, uppercase, only valid keyboard characters
        name = name.upper().strip()[:7]
        self.rival_name = name
        self._rival_name_source = source
        self.rival_name_pending = False
        log.info(
            f"NamePlanner: Preplanned rival name set to '{name}' (source: {source})"
        )

    def set_rival_name(self, name: str):
        """Set the rival's name (legacy method, use set_preplanned_rival_name)."""
        self.set_preplanned_rival_name(name, source="manual")

    def set_current_starter_nickname(self, nickname: str):
        """
        Set the nickname for the current starter Pokemon being named.
        Called when entering the nickname screen after obtaining a starter.

        Args:
            nickname: The nickname (max 10 chars, uppercase)
        """
        nickname = nickname.upper().strip()[:10]
        self._current_starter_nickname = nickname
        log.info(f"NamePlanner: Set current starter nickname to '{nickname}'")

    def set_pokemon_nickname(self, species: str, nickname: str):
        """Set a nickname for a Pokemon species."""
        nickname = nickname.upper().strip()[
            :10
        ]  # Pokemon nicknames can be up to 10 chars
        self.pokemon_nicknames[species.upper()] = nickname
        log.info(f"NamePlanner: {species} nicknamed '{nickname}'")

    def start_typing(self, name: str):
        """
        Start typing a name - generates the full navigation sequence.

        Args:
            name: The name to type
        """
        name = name.upper()

        # Deduplication check: Don't re-type the same name we just confirmed
        # This handles cases where game state is stale/flaky and re-triggers detection
        if self.last_confirmed_name == name:
            log.info(
                f"NamePlanner: Skipping typing of recently confirmed name '{name}'"
            )
            # Ensure flag is set so we don't try to confirm again
            self.confirmation_sent = True
            return

        # Starting a NEW name entry
        self.confirmation_sent = False
        self.current_name = name
        self.current_char_index = 0

        # Generate typing sequence from keyboard tracker
        kb = get_keyboard_tracker()
        self.typing_sequence = kb.get_typing_sequence(self.current_name)

        log.info(
            f"NamePlanner: Starting to type '{self.current_name}' ({len(self.typing_sequence)} chars)"
        )
        for step in self.typing_sequence:
            log.debug(f"  -> '{step['char']}': {step['path']}")

    def set_confirmation_sent(self, sent: bool = True):
        """Set whether the final START confirmation has been sent."""
        self.confirmation_sent = sent
        if sent and self.current_name:
            self.last_confirmed_name = self.current_name
            log.info(f"NamePlanner: Marked '{self.current_name}' as confirmed")
        log.info(f"NamePlanner: Confirmation sent flag set to {sent}")

    def get_next_action(self) -> Optional[str]:
        """
        Get the next action to type the current character.

        Returns:
            Action string like "D;R;R;A;" or None if done
        """
        if self.confirmation_sent:
            return None

        if self.current_char_index >= len(self.typing_sequence):
            return None  # Done typing

        step = self.typing_sequence[self.current_char_index]
        return step["path"]

    def get_current_step(self) -> Optional[dict]:
        """Get info about the current character being typed."""
        if self.current_char_index >= len(self.typing_sequence):
            return None
        return self.typing_sequence[self.current_char_index]

    def advance(self):
        """Advance to the next character after successful input."""
        if self.current_char_index < len(self.typing_sequence):
            step = self.typing_sequence[self.current_char_index]
            log.info(
                f"NamePlanner: Typed '{step['char']}' ({self.current_char_index + 1}/{len(self.typing_sequence)})"
            )
            self.current_char_index += 1

    def is_done_typing(self) -> bool:
        """Check if we've finished typing the current name."""
        if not self.current_name or not self.typing_sequence:
            return False
        return self.current_char_index >= len(self.typing_sequence)

    def get_progress_string(self) -> str:
        """Get a string showing typing progress like 'LA__' for LASS."""
        if not self.current_name:
            return ""

        typed = self.current_name[: self.current_char_index]
        remaining = "_" * (len(self.current_name) - self.current_char_index)
        return typed + remaining

    def get_rival_prompt(self) -> str:
        """Get the prompt showing which rival name was selected."""
        if self.rival_name:
            source_info = (
                f" (source: {self._rival_name_source})"
                if self._rival_name_source != "none"
                else ""
            )
            return f"RIVAL NAME: {self.rival_name}{source_info}"
        else:
            # This shouldn't happen, but have a fallback
            suggestions = ", ".join(RIVAL_NAME_SUGGESTIONS[:5])
            return f"RIVAL NAME OPTIONS: {suggestions}"

    def reset(self):
        """Reset typing state for a new name (but preserve preplanned names).

        NOTE: We intentionally do NOT reset confirmation_sent here.
        This prevents a race condition where the game state still shows
        name_entry_state after we've sent START to confirm. If we reset
        confirmation_sent=False here, the next cycle would see the stale
        keyboard state and try to re-confirm, causing double START presses.

        confirmation_sent is only cleared when we start typing a NEW name
        (in scenario_manager._check_name_entry when start_typing is called).
        """
        self.current_name = None
        self.current_char_index = 0
        self.typing_sequence = []
        self.name_type = None
        # DO NOT reset confirmation_sent - prevents race condition with stale game state
        self._current_starter_nickname = None
        log.info(
            f"NamePlanner: Reset typing state (confirmation_sent={self.confirmation_sent} preserved)"
        )

    def full_reset(self):
        """Full reset including preplanned names (for new run)."""
        self.reset()
        self.rival_name = None
        self._rival_name_source = "none"
        self.pokemon_nicknames = {}
        self.last_confirmed_name = None
        log.info("NamePlanner: Full reset (including preplanned names)")

    def get_rival_name_info(self) -> dict:
        """Get info about the preplanned rival name."""
        return {
            "name": self.rival_name,
            "source": self._rival_name_source,
            "is_set": self.rival_name is not None,
        }

    def to_dict(self) -> dict:
        """Serialize preplanned names for persistence."""
        return {
            "rival_name": self.rival_name,
            "rival_name_source": self._rival_name_source,
            "pokemon_nicknames": self.pokemon_nicknames,
        }

    def from_dict(self, data: dict):
        """Restore preplanned names from persistence."""
        if data.get("rival_name"):
            self.rival_name = data["rival_name"]
            self._rival_name_source = data.get("rival_name_source", "persisted")
        if data.get("pokemon_nicknames"):
            self.pokemon_nicknames = data["pokemon_nicknames"]
        log.info(f"NamePlanner: Restored from persistence - rival: {self.rival_name}")


# Global singleton
_planner_instance = None


def get_name_planner() -> NamePlanner:
    """Get the global NamePlanner instance."""
    global _planner_instance
    if _planner_instance is None:
        _planner_instance = NamePlanner()
    return _planner_instance
