#!/usr/bin/env python3
"""
Generate IMAGE_PROMPTS.md documentation from data/image_prompts.yaml.

This script reads the single source of truth (YAML) and generates
human-readable markdown documentation. Run this whenever the YAML
file is updated to keep docs in sync.

Usage:
    python scripts/generate_prompt_docs.py

The script also performs basic validation:
- Checks all required fields are present
- Warns about missing achievement types
- Validates field lengths
"""

import sys
import os
from pathlib import Path
from datetime import datetime

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml")
    sys.exit(1)


# Expected achievement types (from achievement_tracker.py)
EXPECTED_ACHIEVEMENTS = {
    "stream_start",
    "first_pokemon",
    "route_1_flower",
    "first_catch",
    "viridian_forest_break",
    "team_rocket_first",
    "starter_evolution_1",
    "starter_evolution_2",
    "badge_boulder",
    "badge_cascade",
    "badge_thunder",
    "badge_rainbow",
    "badge_soul",
    "badge_marsh",
    "badge_volcano",
    "badge_earth",
    "ss_anne_deck",
    "pokemon_tower_spooked",
    "game_corner_slots",
    "fighting_dojo",
    "safari_zone_explorer",
    "cerulean_cape",
    "mt_moon_exit",
    "rock_tunnel_exit",
    "cycling_road",
    "seafoam_islands",
    "route_12_fishing",
    "pewter_gym_entrance",
    "indigo_plateau",
    "daycare_visit",
    "legendary_articuno",
    "legendary_zapdos",
    "legendary_moltres",
    "legendary_mewtwo",
    "pokemon_champion",
}

REQUIRED_FIELDS = {"setting", "mood_expression", "action", "extras"}
MAX_FIELD_LENGTH = 150  # Reasonable limit for SD prompts


def load_yaml(yaml_path: Path) -> dict:
    """Load the image prompts YAML file."""
    with open(yaml_path, "r") as f:
        return yaml.safe_load(f)


def validate_prompts(data: dict) -> list:
    """Validate the prompt data and return list of warnings."""
    warnings = []
    checkpoints = data.get("checkpoints", {})

    # Check for missing achievements
    defined_keys = set(checkpoints.keys())
    missing = EXPECTED_ACHIEVEMENTS - defined_keys
    if missing:
        warnings.append(f"Missing achievement types: {', '.join(sorted(missing))}")

    extra = defined_keys - EXPECTED_ACHIEVEMENTS
    if extra:
        warnings.append(
            f"Extra achievement types not in code: {', '.join(sorted(extra))}"
        )

    # Validate each checkpoint
    for key, prompt in checkpoints.items():
        # Check required fields
        for field in REQUIRED_FIELDS:
            if field not in prompt:
                warnings.append(f"{key}: Missing required field '{field}'")
            elif not prompt[field]:
                warnings.append(f"{key}: Empty field '{field}'")
            elif len(prompt[field]) > MAX_FIELD_LENGTH:
                warnings.append(
                    f"{key}: Field '{field}' exceeds {MAX_FIELD_LENGTH} chars "
                    f"({len(prompt[field])} chars)"
                )

        # Check name and description
        if "name" not in prompt:
            warnings.append(f"{key}: Missing 'name' field")
        if "description" not in prompt:
            warnings.append(f"{key}: Missing 'description' field")

    return warnings


def generate_markdown(data: dict) -> str:
    """Generate markdown documentation from YAML data."""
    lines = []

    # Header
    lines.append("# Image Prompts Reference")
    lines.append("")
    lines.append("> **Auto-generated** from `data/image_prompts.yaml`")
    lines.append(f"> Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(">")
    lines.append("> Do not edit this file directly. Edit the YAML source and run:")
    lines.append("> `python scripts/generate_prompt_docs.py`")
    lines.append("")

    # Table of Contents
    lines.append("## Table of Contents")
    lines.append("")
    lines.append("- [Base Prompt](#base-prompt)")
    lines.append("- [Checkpoint Prompts](#checkpoint-prompts)")

    checkpoints = data.get("checkpoints", {})
    categories = categorize_checkpoints(checkpoints)
    for category_name in categories:
        anchor = category_name.lower().replace(" ", "-").replace("/", "")
        lines.append(f"  - [{category_name}](#{anchor})")

    lines.append("- [Dynamic Template](#dynamic-template)")
    lines.append("- [Negative Prompt](#negative-prompt)")
    lines.append("")

    # Base Prompt
    lines.append("---")
    lines.append("")
    lines.append("## Base Prompt")
    lines.append("")
    lines.append("This is prepended to ALL generated images (constant Lass character):")
    lines.append("")
    lines.append("```")
    lines.append(data.get("base_prompt", "").strip())
    lines.append("```")
    lines.append("")

    # Checkpoint Prompts
    lines.append("---")
    lines.append("")
    lines.append("## Checkpoint Prompts")
    lines.append("")
    lines.append(f"Total checkpoints: **{len(checkpoints)}**")
    lines.append("")

    for category_name, category_keys in categories.items():
        anchor = category_name.lower().replace(" ", "-").replace("/", "")
        lines.append(f"### {category_name}")
        lines.append("")

        for key in category_keys:
            prompt = checkpoints.get(key, {})
            lines.append(f"#### `{key}`")
            lines.append("")
            lines.append(f"**{prompt.get('name', key)}**")
            lines.append("")
            if prompt.get("description"):
                lines.append(f"*{prompt['description']}*")
                lines.append("")

            # Create table for the 4 fields
            lines.append("| Field | Prompt |")
            lines.append("|-------|--------|")
            lines.append(f"| **Setting** | {prompt.get('setting', '-')} |")
            lines.append(
                f"| **Mood/Expression** | {prompt.get('mood_expression', '-')} |"
            )
            lines.append(f"| **Action** | {prompt.get('action', '-')} |")
            lines.append(f"| **Extras** | {prompt.get('extras', '-')} |")
            lines.append("")

    # Dynamic Template
    lines.append("---")
    lines.append("")
    lines.append("## Dynamic Template")
    lines.append("")
    lines.append("Used for CYCLE_CHECKPOINT (progress/fallback) posts where the LLM")
    lines.append("generates prompt components dynamically based on game state.")
    lines.append("")

    dynamic = data.get("dynamic_template", {})
    if dynamic.get("system_prompt"):
        lines.append("### System Prompt")
        lines.append("")
        lines.append("```")
        lines.append(dynamic["system_prompt"].strip())
        lines.append("```")
        lines.append("")

    if dynamic.get("response_format"):
        lines.append("### Expected Response Format")
        lines.append("")
        lines.append("```json")
        lines.append(dynamic["response_format"].strip())
        lines.append("```")
        lines.append("")

    # Negative Prompt
    lines.append("---")
    lines.append("")
    lines.append("## Negative Prompt")
    lines.append("")
    lines.append("Applied to ALL generated images:")
    lines.append("")
    lines.append("```")
    lines.append(data.get("negative_prompt", "").strip())
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


def categorize_checkpoints(checkpoints: dict) -> dict:
    """Organize checkpoints into logical categories."""
    categories = {
        "Stream Events": ["stream_start"],
        "Early Game Milestones": [
            "first_pokemon",
            "route_1_flower",
            "first_catch",
            "viridian_forest_break",
            "team_rocket_first",
        ],
        "Evolution Milestones": ["starter_evolution_1", "starter_evolution_2"],
        "Gym Badges": [
            "badge_boulder",
            "badge_cascade",
            "badge_thunder",
            "badge_rainbow",
            "badge_soul",
            "badge_marsh",
            "badge_volcano",
            "badge_earth",
        ],
        "Scripted Location Moments": [
            "ss_anne_deck",
            "pokemon_tower_spooked",
            "game_corner_slots",
            "fighting_dojo",
            "safari_zone_explorer",
        ],
        "Scenic/Nature Photo Moments": [
            "cerulean_cape",
            "mt_moon_exit",
            "rock_tunnel_exit",
            "cycling_road",
            "seafoam_islands",
            "route_12_fishing",
        ],
        "Milestone Photo Moments": [
            "pewter_gym_entrance",
            "indigo_plateau",
            "daycare_visit",
        ],
        "Legendary Captures": [
            "legendary_articuno",
            "legendary_zapdos",
            "legendary_moltres",
            "legendary_mewtwo",
        ],
        "Endgame": ["pokemon_champion"],
    }

    # Filter to only include keys that exist in checkpoints
    return {
        name: [k for k in keys if k in checkpoints]
        for name, keys in categories.items()
        if any(k in checkpoints for k in keys)
    }


def main():
    """Main entry point."""
    yaml_path = PROJECT_ROOT / "data" / "image_prompts.yaml"
    output_path = PROJECT_ROOT / "docs" / "features" / "IMAGE_PROMPTS.md"

    # Check YAML exists
    if not yaml_path.exists():
        print(f"ERROR: YAML file not found: {yaml_path}")
        sys.exit(1)

    print(f"Loading: {yaml_path}")
    data = load_yaml(yaml_path)

    # Validate
    print("Validating prompts...")
    warnings = validate_prompts(data)
    if warnings:
        print("\nValidation warnings:")
        for w in warnings:
            print(f"  - {w}")
        print()

    # Generate markdown
    print("Generating markdown...")
    markdown = generate_markdown(data)

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(markdown)

    print(f"Generated: {output_path}")
    print(f"Total checkpoints: {len(data.get('checkpoints', {}))}")

    # Return non-zero if there were validation errors (not just warnings)
    missing_achievements = EXPECTED_ACHIEVEMENTS - set(
        data.get("checkpoints", {}).keys()
    )
    if missing_achievements:
        print(f"\nERROR: Missing {len(missing_achievements)} achievement types!")
        sys.exit(1)

    print("\nDone!")


if __name__ == "__main__":
    main()
